CREATE DATABASE Aerolinea;
USE Aerolinea;

CREATE TABLE Cliente(
	id_Cliente INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	nombre_Cliente VARCHAR(40) NOT NULL,
	apellidos_Cliente VARCHAR(40) NOT NULL,
	curp VARCHAR(18) NOT NULL,
	telefono VARCHAR(12) NOT NULL,
	direccion VARCHAR(45) NOT NULL
);

CREATE TABLE Tarjeta_Credito(
	id_Tarjeta_Credito VARCHAR(16) PRIMARY KEY NOT NULL,
	id_Cliente INT NOT NULL,
	nombre VARCHAR(40) NOT NULL,
	apellido VARCHAR(40) NOT NULL,
	CVV varchar(4) NOT NULL,
	fecha_vencimiento DATE NOT NULL,
	FOREIGN KEY(id_Cliente) REFERENCES Cliente(id_Cliente)
);

CREATE TABLE Aeropuerto(
	id_Aeropuerto INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	nombre_Aeropuerto VARCHAR(50) NOT NULL,
	pais VARCHAR(25) NOT NULL,
	localidad VARCHAR(50) NOT NULL
);

CREATE TABLE Avion(
	id_Avion INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	no_Plazas INT NOT NULL,
	no_Plazas_Dis INT NOT NULL,
	id_Aeropuerto INT NOT NULL,
	FOREIGN KEY(id_Aeropuerto) REFERENCES Aeropuerto(id_Aeropuerto)
);

CREATE TABLE Vuelo(
	id_Vuelo INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	id_Avion INT NOT NULL,
	fecha_Salida DATETIME NOT NULL,
	fecha_Llegada DATETIME NOT NULL,
	id_aeropuerto_Salida INT NOT NULL,
	id_aeropuerto_Llegada INT NOT NULL,
	precio decimal(10,2) NOT NULL,
	FOREIGN KEY(id_Avion) REFERENCES Avion(id_Avion),
	FOREIGN KEY(id_aeropuerto_Salida) REFERENCES Aeropuerto(id_Aeropuerto),
	FOREIGN KEY(id_aeropuerto_Llegada) REFERENCES Aeropuerto(id_Aeropuerto)
);

CREATE TABLE Reservacion(
	id_Reserva INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	id_Cliente INT NOT NULL,
	id_Vuelo INT NOT NULL,
	plazas_compradas INT NOT NULL,
	FOREIGN KEY(id_Cliente) REFERENCES Cliente(id_Cliente),
	FOREIGN KEY(id_Vuelo) REFERENCES Vuelo(id_Vuelo)
);

CREATE TABLE Asiento(
	id_Asiento INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id_Avion INT NOT NULL,
	clase VARCHAR(20) NOT NULL,
	columna INT NOT NULL,
	fila VARCHAR(1) NOT NULL,
	FOREIGN KEY(id_Avion) REFERENCES Avion(id_Avion)
);

CREATE TABLE Pase_Abordo(
	id_Pase INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	id_Reserva INT NOT NULL,
	id_Cliente INT NOT NULL,
	id_Asiento INT NOT NULL,

	FOREIGN KEY(id_Cliente) REFERENCES Cliente(id_Cliente),
	FOREIGN KEY(id_Reserva) REFERENCES Reservacion(id_Reserva),
	FOREIGN KEY(id_Asiento) REFERENCES Asiento(id_Asiento)
);

CREATE TRIGGER asientos_ocupados AFTER INSERT ON Pase_Abordo FOR EACH ROW
	UPDATE Avion SET no_Plazas_Dis = no_Plazas_Dis - 1 WHERE id_Avion = NEW.id_Avion;
	
INSERT INTO Aeropuerto(nombre_Aeropuerto, pais, localidad) VALUES ("AICM", "México", "Ciudad de México");
INSERT INTO Aeropuerto(nombre_aeropuerto, pais, localidad) VALUES ("AIFA", "México", "Estado de México");
INSERT INTO Aeropuerto(nombre_aeropuerto, pais, localidad) VALUES ("Cancún", "México", "Quintana Roo");
INSERT INTO Aeropuerto(nombre_aeropuerto, pais, localidad) VALUES ("Aguascalientes", "México", "Aguascalientes");
INSERT INTO Aeropuerto(nombre_aeropuerto, pais, localidad) VALUES ("Klaipeda Palanga Palanga International", "Lituania", "Klaipeda/Palanga");
INSERT INTO Aeropuerto(nombre_aeropuerto, pais, localidad) VALUES ("Aeropuerto Adolfo Súarez Madrid-Barajas", "España", "Madrid");

INSERT INTO Avion(no_Plazas, no_Plazas_Dis, id_Aeropuerto) VALUES (96, 96, 1);
INSERT INTO Avion(no_Plazas, no_Plazas_Dis, id_Aeropuerto) VALUES (96, 96, 2);
INSERT INTO Avion(no_Plazas, no_Plazas_Dis, id_Aeropuerto) VALUES (96, 96, 3);
INSERT INTO Avion(no_Plazas, no_Plazas_Dis, id_Aeropuerto) VALUES (96, 96, 4);
INSERT INTO Avion(no_Plazas, no_Plazas_Dis, id_Aeropuerto) VALUES (96, 96, 5);

INSERT INTO Vuelo(id_Avion, fecha_Salida, fecha_Llegada, id_aeropuerto_Salida, id_aeropuerto_Llegada, precio) 
	VALUES (1, "2024/05/14 19:00:00", "2024/05/14 22:00:00", 1,2, 742.00);
INSERT INTO Vuelo(id_Avion, fecha_Salida, fecha_Llegada, id_aeropuerto_Salida, id_aeropuerto_Llegada, precio) 
	VALUES (2, "2024/05/15 23:30:00", "2024/05/16 10:00:00", 3,5, 1742.00);
INSERT INTO Vuelo(id_Avion, fecha_Salida, fecha_Llegada, id_aeropuerto_Salida, id_aeropuerto_Llegada, precio) 
	VALUES (3, "2024/05/16 13:30:00", "2024/05/16 17:00:00", 2,4, 1452.00);
INSERT INTO Vuelo(id_Avion, fecha_Salida, fecha_Llegada, id_aeropuerto_Salida, id_aeropuerto_Llegada, precio) 
	VALUES (4, "2024/05/15 09:00:00", "2024/05/15 11:00:00", 1,2, 952.00);
INSERT INTO Vuelo(id_Avion, fecha_Salida, fecha_Llegada, id_aeropuerto_Salida, id_aeropuerto_Llegada, precio) 
	VALUES (5, "2024/05/14 09:00:00", "2024/05/14 13:00:00", 5,6, 513.00);
INSERT INTO Vuelo(id_Avion, fecha_Salida, fecha_Llegada, id_aeropuerto_Salida, id_aeropuerto_Llegada, precio) 
	VALUES (4, "2024/05/14 22:00:00", "2024/05/15 07:00:00", 1,6, 943.00);

INSERT INTO Asiento(id_Avion, clase, columna, fila)
VALUES
	(1, 'Ejecutivo', 1, 'A'),
	(1, 'Ejecutivo', 2, 'A'),
	(1, 'Ejecutivo', 3, 'A'),
	(1, 'Ejecutivo', 4, 'A'),
	(1, 'Ejecutivo', 5, 'A'),
	(1, 'Ejecutivo', 6, 'A'),
	(1, 'Ejecutivo', 7, 'A'),
	(1, 'Ejecutivo', 8, 'A'),
	(1, 'Ejecutivo', 9, 'A'),
	(1, 'Ejecutivo', 10, 'A'),
	(1, 'Ejecutivo', 11, 'A'),
	(1, 'Ejecutivo', 12, 'A'),
	(1, 'Ejecutivo', 13, 'A'),
	(1, 'Ejecutivo', 14, 'A'),
	(1, 'Ejecutivo', 15, 'A'),
	(1, 'Ejecutivo', 16, 'A'),
	(1, 'Ejecutivo', 1, 'B'),
	(1, 'Ejecutivo', 2, 'B'),
	(1, 'Ejecutivo', 3, 'B'),
	(1, 'Ejecutivo', 4, 'B'),
	(1, 'Ejecutivo', 5, 'B'),
	(1, 'Ejecutivo', 6, 'B'),
	(1, 'Ejecutivo', 7, 'B'),
	(1, 'Ejecutivo', 8, 'B'),
	(1, 'Ejecutivo', 9, 'B'),
	(1, 'Ejecutivo', 10, 'B'),
	(1, 'Ejecutivo', 11, 'B'),
	(1, 'Ejecutivo', 12, 'B'),
	(1, 'Ejecutivo', 13, 'B'),
	(1, 'Ejecutivo', 14, 'B'),
	(1, 'Ejecutivo', 15, 'B'),
	(1, 'Ejecutivo', 16, 'B'),
	(1, 'Primera clase', 1, 'C'),
	(1, 'Primera clase', 2, 'C'),
	(1, 'Primera clase', 3, 'C'),
	(1, 'Primera clase', 4, 'C'),
	(1, 'Primera clase', 5, 'C'),
	(1, 'Primera clase', 6, 'C'),
	(1, 'Primera clase', 7, 'C'),
	(1, 'Primera clase', 8, 'C'),
	(1, 'Primera clase', 9, 'C'),
	(1, 'Primera clase', 10, 'C'),
	(1, 'Primera clase', 11, 'C'),
	(1, 'Primera clase', 12, 'C'),
	(1, 'Primera clase', 13, 'C'),
	(1, 'Primera clase', 14, 'C'),
	(1, 'Primera clase', 15, 'C'),
	(1, 'Primera clase', 16, 'C'),
	(1, 'Primera clase', 1, 'D'),
	(1, 'Primera clase', 2, 'D'),
	(1, 'Primera clase', 3, 'D'),
	(1, 'Primera clase', 4, 'D'),
	(1, 'Primera clase', 5, 'D'),
	(1, 'Primera clase', 6, 'D'),
	(1, 'Primera clase', 7, 'D'),
	(1, 'Primera clase', 8, 'D'),
	(1, 'Primera clase', 9, 'D'),
	(1, 'Primera clase', 10, 'D'),
	(1, 'Primera clase', 11, 'D'),
	(1, 'Primera clase', 12, 'D'),
	(1, 'Primera clase', 13, 'D'),
	(1, 'Primera clase', 14, 'D'),
	(1, 'Primera clase', 15, 'D'),
	(1, 'Primera clase', 16, 'D'),
	(1, 'Turista', 1, 'E'),
	(1, 'Turista', 2, 'E'),
	(1, 'Turista', 3, 'E'),
	(1, 'Turista', 4, 'E'),
	(1, 'Turista', 5, 'E'),
	(1, 'Turista', 6, 'E'),
	(1, 'Turista', 7, 'E'),
	(1, 'Turista', 8, 'E'),
	(1, 'Turista', 9, 'E'),
	(1, 'Turista', 10, 'E'),
	(1, 'Turista', 11, 'E'),
	(1, 'Turista', 12, 'E'),
	(1, 'Turista', 13, 'E'),
	(1, 'Turista', 14, 'E'),
	(1, 'Turista', 15, 'E'),
	(1, 'Turista', 16, 'E'),
	(1, 'Turista', 1, 'F'),
	(1, 'Turista', 2, 'F'),
	(1, 'Turista', 3, 'F'),
	(1, 'Turista', 4, 'F'),
	(1, 'Turista', 5, 'F'),
	(1, 'Turista', 6, 'F'),
	(1, 'Turista', 7, 'F'),
	(1, 'Turista', 8, 'F'),
	(1, 'Turista', 9, 'F'),
	(1, 'Turista', 10, 'F'),
	(1, 'Turista', 11, 'F'),
	(1, 'Turista', 12, 'F'),
	(1, 'Turista', 13, 'F'),
	(1, 'Turista', 14, 'F'),
	(1, 'Turista', 15, 'F'),
	(1, 'Turista', 16, 'F'),
	(2, 'Ejecutivo', 1, 'A'),
	(2, 'Ejecutivo', 2, 'A'),
	(2, 'Ejecutivo', 3, 'A'),
	( 2, 'Ejecutivo', 4, 'A'),
	( 2, 'Ejecutivo', 5, 'A'),
	( 2, 'Ejecutivo', 6, 'A'),
	( 2, 'Ejecutivo', 7, 'A'),
	( 2, 'Ejecutivo', 8, 'A'),
	( 2, 'Ejecutivo', 9, 'A'),
	( 2, 'Ejecutivo', 10, 'A'),
	( 2, 'Ejecutivo', 11, 'A'),
	( 2, 'Ejecutivo', 12, 'A'),
	( 2, 'Ejecutivo', 13, 'A'),
	( 2, 'Ejecutivo', 14, 'A'),
	( 2, 'Ejecutivo', 15, 'A'),
	( 2, 'Ejecutivo', 16, 'A'),
	( 2, 'Ejecutivo', 1, 'B'),
	( 2, 'Ejecutivo', 2, 'B'),
	( 2, 'Ejecutivo', 3, 'B'),
	( 2, 'Ejecutivo', 4, 'B'),
	( 2, 'Ejecutivo', 5, 'B'),
	( 2, 'Ejecutivo', 6, 'B'),
	( 2, 'Ejecutivo', 7, 'B'),
	( 2, 'Ejecutivo', 8, 'B'),
	( 2, 'Ejecutivo', 9, 'B'),
	( 2, 'Ejecutivo', 10, 'B'),
	( 2, 'Ejecutivo', 11, 'B'),
	( 2, 'Ejecutivo', 12, 'B'),
	( 2, 'Ejecutivo', 13, 'B'),
	( 2, 'Ejecutivo', 14, 'B'),
	( 2, 'Ejecutivo', 15, 'B'),
	( 2, 'Ejecutivo', 16, 'B'),
	( 2, 'Primera clase', 1, 'C'),
	( 2, 'Primera clase', 2, 'C'),
	( 2, 'Primera clase', 3, 'C'),
	( 2, 'Primera clase', 4, 'C'),
	( 2, 'Primera clase', 5, 'C'),
	( 2, 'Primera clase', 6, 'C'),
	( 2, 'Primera clase', 7, 'C'),
	( 2, 'Primera clase', 8, 'C'),
	( 2, 'Primera clase', 9, 'C'),
	( 2, 'Primera clase', 10, 'C'),
	( 2, 'Primera clase', 11, 'C'),
	( 2, 'Primera clase', 12, 'C'),
	( 2, 'Primera clase', 13, 'C'),
	( 2, 'Primera clase', 14, 'C'),
	( 2, 'Primera clase', 15, 'C'),
	( 2, 'Primera clase', 16, 'C'),
	( 2, 'Primera clase', 1, 'D'),
	( 2, 'Primera clase', 2, 'D'),
	( 2, 'Primera clase', 3, 'D'),
	( 2, 'Primera clase', 4, 'D'),
	( 2, 'Primera clase', 5, 'D'),
	( 2, 'Primera clase', 6, 'D'),
	( 2, 'Primera clase', 7, 'D'),
	( 2, 'Primera clase', 8, 'D'),
	( 2, 'Primera clase', 9, 'D'),
	( 2, 'Primera clase', 10, 'D'),
	( 2, 'Primera clase', 11, 'D'),
	( 2, 'Primera clase', 12, 'D'),
	( 2, 'Primera clase', 13, 'D'),
	( 2, 'Primera clase', 14, 'D'),
	( 2, 'Primera clase', 15, 'D'),
	( 2, 'Primera clase', 16, 'D'),
	( 2, 'Turista', 1, 'E'),
	( 2, 'Turista', 2, 'E'),
	( 2, 'Turista', 3, 'E'),
	( 2, 'Turista', 4, 'E'),
	( 2, 'Turista', 5, 'E'),
	( 2, 'Turista', 6, 'E'),
	( 2, 'Turista', 7, 'E'),
	( 2, 'Turista', 8, 'E'),
	( 2, 'Turista', 9, 'E'),
	( 2, 'Turista', 10, 'E'),
	( 2, 'Turista', 11, 'E'),
	( 2, 'Turista', 12, 'E'),
	( 2, 'Turista', 13, 'E'),
	( 2, 'Turista', 14, 'E'),
	( 2, 'Turista', 15, 'E'),
	( 2, 'Turista', 16, 'E'),
	( 2, 'Turista', 1, 'F'),
	( 2, 'Turista', 2, 'F'),
	( 2, 'Turista', 3, 'F'),
	( 2, 'Turista', 4, 'F'),
	( 2, 'Turista', 5, 'F'),
	( 2, 'Turista', 6, 'F'),
	( 2, 'Turista', 7, 'F'),
	( 2, 'Turista', 8, 'F'),
	( 2, 'Turista', 9, 'F'),
	( 2, 'Turista', 10, 'F'),
	( 2, 'Turista', 11, 'F'),
	( 2, 'Turista', 12, 'F'),
	( 2, 'Turista', 13, 'F'),
	( 2, 'Turista', 14, 'F'),
	( 2, 'Turista', 15, 'F'),
	( 2, 'Turista', 16, 'F'),
	( 3, 'Ejecutivo', 1, 'A'),
	( 3, 'Ejecutivo', 2, 'A'),
	( 3, 'Ejecutivo', 3, 'A'),
	( 3, 'Ejecutivo', 4, 'A'),
	( 3, 'Ejecutivo', 5, 'A'),
	( 3, 'Ejecutivo', 6, 'A'),
	( 3, 'Ejecutivo', 7, 'A'),
	( 3, 'Ejecutivo', 8, 'A'),
	( 3, 'Ejecutivo', 9, 'A'),
	( 3, 'Ejecutivo', 10, 'A'),
	( 3, 'Ejecutivo', 11, 'A'),
	( 3, 'Ejecutivo', 12, 'A'),
	( 3, 'Ejecutivo', 13, 'A'),
	( 3, 'Ejecutivo', 14, 'A'),
	( 3, 'Ejecutivo', 15, 'A'),
	( 3, 'Ejecutivo', 16, 'A'),
	( 3, 'Ejecutivo', 1, 'B'),
	( 3, 'Ejecutivo', 2, 'B'),
	( 3, 'Ejecutivo', 3, 'B'),
	( 3, 'Ejecutivo', 4, 'B'),
	( 3, 'Ejecutivo', 5, 'B'),
	( 3, 'Ejecutivo', 6, 'B'),
	( 3, 'Ejecutivo', 7, 'B'),
	( 3, 'Ejecutivo', 8, 'B'),
	( 3, 'Ejecutivo', 9, 'B'),
	( 3, 'Ejecutivo', 10, 'B'),
	( 3, 'Ejecutivo', 11, 'B'),
	( 3, 'Ejecutivo', 12, 'B'),
	( 3, 'Ejecutivo', 13, 'B'),
	( 3, 'Ejecutivo', 14, 'B'),
	( 3, 'Ejecutivo', 15, 'B'),
	( 3, 'Ejecutivo', 16, 'B'),
	( 3, 'Primera clase', 1, 'C'),
	( 3, 'Primera clase', 2, 'C'),
	( 3, 'Primera clase', 3, 'C'),
	( 3, 'Primera clase', 4, 'C'),
	( 3, 'Primera clase', 5, 'C'),
	( 3, 'Primera clase', 6, 'C'),
	( 3, 'Primera clase', 7, 'C'),
	( 3, 'Primera clase', 8, 'C'),
	( 3, 'Primera clase', 9, 'C'),
	( 3, 'Primera clase', 10, 'C'),
	( 3, 'Primera clase', 11, 'C'),
	( 3, 'Primera clase', 12, 'C'),
	( 3, 'Primera clase', 13, 'C'),
	( 3, 'Primera clase', 14, 'C'),
	( 3, 'Primera clase', 15, 'C'),
	( 3, 'Primera clase', 16, 'C'),
	( 3, 'Primera clase', 1, 'D'),
	( 3, 'Primera clase', 2, 'D'),
	( 3, 'Primera clase', 3, 'D'),
	( 3, 'Primera clase', 4, 'D'),
	( 3, 'Primera clase', 5, 'D'),
	( 3, 'Primera clase', 6, 'D'),
	( 3, 'Primera clase', 7, 'D'),
	( 3, 'Primera clase', 8, 'D'),
	( 3, 'Primera clase', 9, 'D'),
	( 3, 'Primera clase', 10, 'D'),
	( 3, 'Primera clase', 11, 'D'),
	( 3, 'Primera clase', 12, 'D'),
	( 3, 'Primera clase', 13, 'D'),
	( 3, 'Primera clase', 14, 'D'),
	( 3, 'Primera clase', 15, 'D'),
	( 3, 'Primera clase', 16, 'D'),
	( 3, 'Turista', 1, 'E'),
	( 3, 'Turista', 2, 'E'),
	( 3, 'Turista', 3, 'E'),
	( 3, 'Turista', 4, 'E'),
	( 3, 'Turista', 5, 'E'),
	( 3, 'Turista', 6, 'E'),
	( 3, 'Turista', 7, 'E'),
	( 3, 'Turista', 8, 'E'),
	( 3, 'Turista', 9, 'E'),
	( 3, 'Turista', 10, 'E'),
	( 3, 'Turista', 11, 'E'),
	( 3, 'Turista', 12, 'E'),
	( 3, 'Turista', 13, 'E'),
	( 3, 'Turista', 14, 'E'),
	( 3, 'Turista', 15, 'E'),
	( 3, 'Turista', 16, 'E'),
	( 3, 'Turista', 1, 'F'),
	( 3, 'Turista', 2, 'F'),
	( 3, 'Turista', 3, 'F'),
	( 3, 'Turista', 4, 'F'),
	( 3, 'Turista', 5, 'F'),
	( 3, 'Turista', 6, 'F'),
	( 3, 'Turista', 7, 'F'),
	( 3, 'Turista', 8, 'F'),
	( 3, 'Turista', 9, 'F'),
	( 3, 'Turista', 10, 'F'),
	( 3, 'Turista', 11, 'F'),
	( 3, 'Turista', 12, 'F'),
	( 3, 'Turista', 13, 'F'),
	( 3, 'Turista', 14, 'F'),
	( 3, 'Turista', 15, 'F'),
	( 3, 'Turista', 16, 'F'),
	( 4, 'Ejecutivo', 1, 'A'),
	( 4, 'Ejecutivo', 2, 'A'),
	( 4, 'Ejecutivo', 3, 'A'),
	( 4, 'Ejecutivo', 4, 'A'),
	( 4, 'Ejecutivo', 5, 'A'),
	( 4, 'Ejecutivo', 6, 'A'),
	( 4, 'Ejecutivo', 7, 'A'),
	( 4, 'Ejecutivo', 8, 'A'),
	( 4, 'Ejecutivo', 9, 'A'),
	( 4, 'Ejecutivo', 10, 'A'),
	( 4, 'Ejecutivo', 11, 'A'),
	( 4, 'Ejecutivo', 12, 'A'),
	( 4, 'Ejecutivo', 13, 'A'),
	( 4, 'Ejecutivo', 14, 'A'),
	( 4, 'Ejecutivo', 15, 'A'),
	( 4, 'Ejecutivo', 16, 'A'),
	( 4, 'Ejecutivo', 1, 'B'),
	( 4, 'Ejecutivo', 2, 'B'),
	( 4, 'Ejecutivo', 3, 'B'),
	( 4, 'Ejecutivo', 4, 'B'),
	( 4, 'Ejecutivo', 5, 'B'),
	( 4, 'Ejecutivo', 6, 'B'),
	( 4, 'Ejecutivo', 7, 'B'),
	( 4, 'Ejecutivo', 8, 'B'),
	( 4, 'Ejecutivo', 9, 'B'),
	( 4, 'Ejecutivo', 10, 'B'),
	( 4, 'Ejecutivo', 11, 'B'),
	( 4, 'Ejecutivo', 12, 'B'),
	( 4, 'Ejecutivo', 13, 'B'),
	( 4, 'Ejecutivo', 14, 'B'),
	( 4, 'Ejecutivo', 15, 'B'),
	( 4, 'Ejecutivo', 16, 'B'),
	( 4, 'Primera clase', 1, 'C'),
	( 4, 'Primera clase', 2, 'C'),
	( 4, 'Primera clase', 3, 'C'),
	( 4, 'Primera clase', 4, 'C'),
	( 4, 'Primera clase', 5, 'C'),
	( 4, 'Primera clase', 6, 'C'),
	( 4, 'Primera clase', 7, 'C'),
	( 4, 'Primera clase', 8, 'C'),
	( 4, 'Primera clase', 9, 'C'),
	( 4, 'Primera clase', 10, 'C'),
	( 4, 'Primera clase', 11, 'C'),
	( 4, 'Primera clase', 12, 'C'),
	( 4, 'Primera clase', 13, 'C'),
	( 4, 'Primera clase', 14, 'C'),
	( 4, 'Primera clase', 15, 'C'),
	( 4, 'Primera clase', 16, 'C'),
	( 4, 'Primera clase', 1, 'D'),
	( 4, 'Primera clase', 2, 'D'),
	( 4, 'Primera clase', 3, 'D'),
	( 4, 'Primera clase', 4, 'D'),
	( 4, 'Primera clase', 5, 'D'),
	( 4, 'Primera clase', 6, 'D'),
	( 4, 'Primera clase', 7, 'D'),
	( 4, 'Primera clase', 8, 'D'),
	( 4, 'Primera clase', 9, 'D'),
	( 4, 'Primera clase', 10, 'D'),
	( 4, 'Primera clase', 11, 'D'),
	( 4, 'Primera clase', 12, 'D'),
	( 4, 'Primera clase', 13, 'D'),
	( 4, 'Primera clase', 14, 'D'),
	( 4, 'Primera clase', 15, 'D'),
	( 4, 'Primera clase', 16, 'D'),
	( 4, 'Turista', 1, 'E'),
	( 4, 'Turista', 2, 'E'),
	( 4, 'Turista', 3, 'E'),
	( 4, 'Turista', 4, 'E'),
	( 4, 'Turista', 5, 'E'),
	( 4, 'Turista', 6, 'E'),
	( 4, 'Turista', 7, 'E'),
	( 4, 'Turista', 8, 'E'),
	( 4, 'Turista', 9, 'E'),
	( 4, 'Turista', 10, 'E'),
	( 4, 'Turista', 11, 'E'),
	( 4, 'Turista', 12, 'E'),
	( 4, 'Turista', 13, 'E'),
	( 4, 'Turista', 14, 'E'),
	( 4, 'Turista', 15, 'E'),
	( 4, 'Turista', 16, 'E'),
	( 4, 'Turista', 1, 'F'),
	( 4, 'Turista', 2, 'F'),
	( 4, 'Turista', 3, 'F'),
	( 4, 'Turista', 4, 'F'),
	( 4, 'Turista', 5, 'F'),
	( 4, 'Turista', 6, 'F'),
	( 4, 'Turista', 7, 'F'),
	( 4, 'Turista', 8, 'F'),
	( 4, 'Turista', 9, 'F'),
	( 4, 'Turista', 10, 'F'),
	( 4, 'Turista', 11, 'F'),
	( 4, 'Turista', 12, 'F'),
	( 4, 'Turista', 13, 'F'),
	( 4, 'Turista', 14, 'F'),
	( 4, 'Turista', 15, 'F'),
	( 4, 'Turista', 16, 'F'),
	( 5, 'Ejecutivo', 1, 'A'),
	( 5, 'Ejecutivo', 2, 'A'),
	( 5, 'Ejecutivo', 3, 'A'),
	( 5, 'Ejecutivo', 4, 'A'),
	( 5, 'Ejecutivo', 5, 'A'),
	( 5, 'Ejecutivo', 6, 'A'),
	( 5, 'Ejecutivo', 7, 'A'),
	( 5, 'Ejecutivo', 8, 'A'),
	( 5, 'Ejecutivo', 9, 'A'),
	( 5, 'Ejecutivo', 10, 'A'),
	( 5, 'Ejecutivo', 11, 'A'),
	( 5, 'Ejecutivo', 12, 'A'),
	( 5, 'Ejecutivo', 13, 'A'),
	( 5, 'Ejecutivo', 14, 'A'),
	( 5, 'Ejecutivo', 15, 'A'),
	( 5, 'Ejecutivo', 16, 'A'),
	( 5, 'Ejecutivo', 1, 'B'),
	( 5, 'Ejecutivo', 2, 'B'),
	( 5, 'Ejecutivo', 3, 'B'),
	( 5, 'Ejecutivo', 4, 'B'),
	( 5, 'Ejecutivo', 5, 'B'),
	( 5, 'Ejecutivo', 6, 'B'),
	( 5, 'Ejecutivo', 7, 'B'),
	( 5, 'Ejecutivo', 8, 'B'),
	( 5, 'Ejecutivo', 9, 'B'),
	( 5, 'Ejecutivo', 10, 'B'),
	( 5, 'Ejecutivo', 11, 'B'),
	( 5, 'Ejecutivo', 12, 'B'),
	( 5, 'Ejecutivo', 13, 'B'),
	( 5, 'Ejecutivo', 14, 'B'),
	( 5, 'Ejecutivo', 15, 'B'),
	( 5, 'Ejecutivo', 16, 'B'),
	( 5, 'Primera clase', 1, 'C'),
	( 5, 'Primera clase', 2, 'C'),
	( 5, 'Primera clase', 3, 'C'),
	( 5, 'Primera clase', 4, 'C'),
	( 5, 'Primera clase', 5, 'C'),
	( 5, 'Primera clase', 6, 'C'),
	( 5, 'Primera clase', 7, 'C'),
	( 5, 'Primera clase', 8, 'C'),
	( 5, 'Primera clase', 9, 'C'),
	( 5, 'Primera clase', 10, 'C'),
	( 5, 'Primera clase', 11, 'C'),
	( 5, 'Primera clase', 12, 'C'),
	( 5, 'Primera clase', 13, 'C'),
	( 5, 'Primera clase', 14, 'C'),
	( 5, 'Primera clase', 15, 'C'),
	( 5, 'Primera clase', 16, 'C'),
	( 5, 'Primera clase', 1, 'D'),
	( 5, 'Primera clase', 2, 'D'),
	( 5, 'Primera clase', 3, 'D'),
	( 5, 'Primera clase', 4, 'D'),
	( 5, 'Primera clase', 5, 'D'),
	( 5, 'Primera clase', 6, 'D'),
	( 5, 'Primera clase', 7, 'D'),
	( 5, 'Primera clase', 8, 'D'),
	( 5, 'Primera clase', 9, 'D'),
	( 5, 'Primera clase', 10, 'D'),
	( 5, 'Primera clase', 11, 'D'),
	( 5, 'Primera clase', 12, 'D'),
	( 5, 'Primera clase', 13, 'D'),
	( 5, 'Primera clase', 14, 'D'),
	( 5, 'Primera clase', 15, 'D'),
	( 5, 'Primera clase', 16, 'D'),
	( 5, 'Turista', 1, 'E'),
	( 5, 'Turista', 2, 'E'),
	( 5, 'Turista', 3, 'E'),
	( 5, 'Turista', 4, 'E'),
	( 5, 'Turista', 5, 'E'),
	( 5, 'Turista', 6, 'E'),
	( 5, 'Turista', 7, 'E'),
	( 5, 'Turista', 8, 'E'),
	( 5, 'Turista', 9, 'E'),
	( 5, 'Turista', 10, 'E'),
	( 5, 'Turista', 11, 'E'),
	( 5, 'Turista', 12, 'E'),
	( 5, 'Turista', 13, 'E'),
	( 5, 'Turista', 14, 'E'),
	( 5, 'Turista', 15, 'E'),
	( 5, 'Turista', 16, 'E'),
	( 5, 'Turista', 1, 'F'),
	( 5, 'Turista', 2, 'F'),
	( 5, 'Turista', 3, 'F'),
	( 5, 'Turista', 4, 'F'),
	( 5, 'Turista', 5, 'F'),
	( 5, 'Turista', 6, 'F'),
	( 5, 'Turista', 7, 'F'),
	( 5, 'Turista', 8, 'F'),
	( 5, 'Turista', 9, 'F'),
	( 5, 'Turista', 10, 'F'),
	( 5, 'Turista', 11, 'F'),
	( 5, 'Turista', 12, 'F'),
	( 5, 'Turista', 13, 'F'),
	( 5, 'Turista', 14, 'F'),
	( 5, 'Turista', 15, 'F'),
	( 5, 'Turista', 16, 'F');


